// Generated by pylon codegen client. Do not edit.

export type EntityName = "User" | "Organization" | "OrgMember" | "Invitation" | "Subscription" | "ApiKey" | "AuditEvent";

export const ENTITIES: EntityName[] = ["User", "Organization", "OrgMember", "Invitation", "Subscription", "ApiKey", "AuditEvent"];

export interface User {
  id: string;
  email: string;
  displayName: string;
  avatarColor?: string;
  passwordHash?: string;
  createdAt: string;
}

export interface Organization {
  id: string;
  name: string;
  slug: string;
  logoUrl?: string;
  plan: string;
  trialEndsAt?: string;
  createdBy: string;
  createdAt: string;
}

export interface OrgMember {
  id: string;
  userId: string;
  orgId: string;
  role: string;
  joinedAt: string;
}

export interface Invitation {
  id: string;
  orgId: string;
  email: string;
  role: string;
  token: string;
  invitedBy: string;
  acceptedAt?: string;
  expiresAt: string;
  createdAt: string;
}

export interface Subscription {
  id: string;
  orgId: string;
  status: string;
  plan: string;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  seats: number;
  currentPeriodEnd?: string;
  createdAt: string;
}

export interface ApiKey {
  id: string;
  orgId: string;
  name: string;
  prefix: string;
  hash: string;
  createdBy: string;
  lastUsedAt?: string;
  createdAt: string;
}

export interface AuditEvent {
  id: string;
  orgId: string;
  actorId: string;
  kind: string;
  metaJson?: string;
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Runtime client
// ---------------------------------------------------------------------------

const DEFAULT_BASE_URL = "http://localhost:4321";

async function _request(baseUrl: string, method: string, path: string, body?: unknown, token?: string): Promise<unknown> {
  const headers: Record<string, string> = {};
  if (body) headers["Content-Type"] = "application/json";
  if (token) headers["Authorization"] = `Bearer ${token}`;
  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as Record<string, unknown>;
    const errorObj = err?.error as Record<string, unknown> | undefined;
    throw new Error((errorObj?.message as string) ?? `HTTP ${res.status}`);
  }
  return res.json();
}

// ---------------------------------------------------------------------------
// Rooms
// ---------------------------------------------------------------------------

export interface RoomPeer {
  user_id: string;
  data: any;
  joined_at: string;
}

export interface RoomSnapshot {
  room: string;
  peers: RoomPeer[];
}

export interface RoomClient {
  join(room: string, data?: Record<string, any>): Promise<RoomSnapshot>;
  leave(room: string): Promise<void>;
  setPresence(room: string, data: Record<string, any>): Promise<void>;
  broadcast(room: string, topic: string, data: any): Promise<void>;
  getMembers(room: string): Promise<RoomPeer[]>;
  listRooms(): Promise<Array<{ name: string; members: number }>>;
}

export interface AgentDBClient {
  list(entity: EntityName): Promise<Record<string, unknown>[]>;
  get(entity: EntityName, id: string): Promise<Record<string, unknown> | null>;
  insert(entity: EntityName, data: Record<string, unknown>): Promise<{ id: string }>;
  update(entity: EntityName, id: string, data: Record<string, unknown>): Promise<{ updated: boolean }>;
  remove(entity: EntityName, id: string): Promise<{ deleted: boolean }>;
  action(name: ActionName, input: Record<string, unknown>): Promise<ActionResult>;
  actions: Actions;
  rooms: RoomClient;
}

export interface ActionResult {
  action: string;
  input: Record<string, unknown>;
  executed: boolean;
}

export interface Actions {
}

function _createRoomClient(baseUrl: string, token?: string): RoomClient {
  const req = (method: string, path: string, body?: unknown) => _request(baseUrl, method, path, body, token);
  return {
    async join(room, data = {}) {
      const res = await req("POST", "/api/rooms/join", { room, data });
      return (res as any).snapshot as RoomSnapshot;
    },
    async leave(room) {
      await req("POST", "/api/rooms/leave", { room });
    },
    async setPresence(room, data) {
      await req("POST", "/api/rooms/presence", { room, data });
    },
    async broadcast(room, topic, data) {
      await req("POST", "/api/rooms/broadcast", { room, topic, data });
    },
    async getMembers(room) {
      const res = await req("GET", `/api/rooms/${encodeURIComponent(room)}`);
      return (res as any).members as RoomPeer[];
    },
    async listRooms() {
      const res = await req("GET", "/api/rooms");
      return res as Array<{ name: string; members: number }>;
    },
  };
}

export function createClient(baseUrl: string = DEFAULT_BASE_URL, token?: string): AgentDBClient {
  const req = (method: string, path: string, body?: unknown) => _request(baseUrl, method, path, body, token);

  const actions: Actions = {
  };

  return {
    list: (entity) => req("GET", `/api/entities/${entity}`) as Promise<Record<string, unknown>[]>,
    get: (entity, id) => req("GET", `/api/entities/${entity}/${id}`).then(r => r as Record<string, unknown>).catch(() => null),
    insert: (entity, data) => req("POST", `/api/entities/${entity}`, data) as Promise<{ id: string }>,
    update: (entity, id, data) => req("PATCH", `/api/entities/${entity}/${id}`, data) as Promise<{ updated: boolean }>,
    remove: (entity, id) => req("DELETE", `/api/entities/${entity}/${id}`) as Promise<{ deleted: boolean }>,
    action: (name, input) => req("POST", `/api/actions/${name}`, input) as Promise<ActionResult>,
    actions,
    rooms: _createRoomClient(baseUrl, token),
  };
}

// ---------------------------------------------------------------------------
// Server Actions (Next.js App Router compatible)
// ---------------------------------------------------------------------------

/** Create a server-side client for use in Next.js Server Actions / RSC. */
export function createServerClient(
  baseUrl: string = process.env.PYLON_URL ?? DEFAULT_BASE_URL,
  token?: string
): AgentDBClient {
  return createClient(baseUrl, token);
}

// ---------------------------------------------------------------------------
// React 19 use() compatible promises
// ---------------------------------------------------------------------------

/** Pre-fetch data as a promise for React 19 use() hook. */
export function prefetch(client: AgentDBClient, entity: EntityName): Promise<Record<string, unknown>[]> {
  return client.list(entity);
}

/** Pre-fetch a single row for React 19 use() hook. */
export function prefetchOne(client: AgentDBClient, entity: EntityName, id: string): Promise<Record<string, unknown> | null> {
  return client.get(entity, id);
}

// ---------------------------------------------------------------------------
// AppSchema — types consumed by @pylon/react's createTypedDb<S>()
// ---------------------------------------------------------------------------

export interface Entities {
  User: User;
  Organization: Organization;
  OrgMember: OrgMember;
  Invitation: Invitation;
  Subscription: Subscription;
  ApiKey: ApiKey;
  AuditEvent: AuditEvent;
}

export interface Functions {
}

export interface Queries {
}

/** Top-level app schema — pass to @pylon/react's createTypedDb<AppSchema>(). */
export interface AppSchema {
  entities: Entities;
  functions: Functions;
  queries: Queries;
}

// ---------------------------------------------------------------------------
// Error codes
// ---------------------------------------------------------------------------

export type AgentDBErrorCode =
  | "AUTH_REQUIRED"
  | "UPGRADE_FAILED"
  | "INVALID_CODE"
  | "OAUTH_INVALID_STATE"
  | "OAUTH_TOKEN_EXCHANGE_FAILED"
  | "PROVIDER_NOT_FOUND"
  | "SESSION_EXPIRED"
  | "SESSION_NOT_FOUND"
  | "FORBIDDEN"
  | "POLICY_DENIED"
  | "UNAUTHORIZED"
  | "INVALID_JSON"
  | "INVALID_ARGS"
  | "INVALID_COLUMN"
  | "INVALID_QUERY"
  | "INVALID_DATA"
  | "INVALID_FILE_ID"
  | "MISSING_EMAIL"
  | "MISSING_USER_ID"
  | "MISSING_CODE"
  | "MISSING_FIELD"
  | "MISSING_ROOM"
  | "MISSING_TOPIC"
  | "MISSING_NAME"
  | "MISSING_OPERATIONS"
  | "PAYLOAD_TOO_LARGE"
  | "NOT_FOUND"
  | "ENTITY_NOT_FOUND"
  | "ACTION_NOT_FOUND"
  | "FN_NOT_FOUND"
  | "FILE_NOT_FOUND"
  | "SHARD_NOT_FOUND"
  | "RELATION_NOT_FOUND"
  | "QUERY_FAILED"
  | "INSERT_FAILED"
  | "UPDATE_FAILED"
  | "DELETE_FAILED"
  | "SCHEMA_INIT_FAILED"
  | "LOCK_FAILED"
  | "NESTED_TRANSACTION"
  | "EXPORT_FAILED"
  | "NOT_SUPPORTED"
  | "NOT_IMPLEMENTED"
  | "NOT_AVAILABLE"
  | "RATE_LIMITED"
  | "METHOD_NOT_ALLOWED"
  | "PROTOCOL_ERROR"
  | "RUNNER_EXITED"
  | "RUNNER_NOT_STARTED"
  | "IO_ERROR"
  | "AI_NOT_CONFIGURED"
  | "AI_REQUEST_FAILED"
  | "EMAIL_SEND_FAILED"
  | "WORKFLOW_START_FAILED"
  | "WORKFLOW_ADVANCE_FAILED"
  | "WORKFLOW_EVENT_FAILED"
  | "WORKFLOW_CANCEL_FAILED"
  | "INPUT_REJECTED"
  | "SUBSCRIBE_FAILED"
  | "SHARDS_NOT_AVAILABLE";

export interface AgentDBError {
  code: AgentDBErrorCode;
  message: string;
  hint?: string;
}
